services:
  mysql:
    image: mysql:8.4
    container_name: boutique_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boutique
      MYSQL_USER: boutique
      MYSQL_PASSWORD: boutique123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

    networks:
      - boutique-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin:latest

    container_name: boutique_phpmyadmin

    restart: unless-stopped

    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - boutique-network


networks:
  boutique-network:
    driver: bridge


volumes:
  mysql_data: