FROM node:22-alpine

WORKDIR /app

ARG SERVICE_NAME

ENV SERVICE_NAME=${SERVICE_NAME}

COPY . .

RUN npm install -g pnpm

RUN CI=true pnpm install --frozen-lockfile --config.confirmModulesPurge=false

RUN if [ -f "backend/services/${SERVICE_NAME}/prisma/schema.prisma" ]; then \
      pnpm -C backend/services/${SERVICE_NAME} exec prisma generate; \
    fi

EXPOSE 4000

CMD ["sh", "-c", "cd backend/services/$SERVICE_NAME && pnpm start"]