FROM node:22-alpine
WORKDIR /app
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
COPY . .
RUN npm install -g pnpm
RUN CI=true pnpm install --frozen-lockfile --config.confirmModulesPurge=false
EXPOSE 4000
CMD ["sh", "-c", "pnpm -C backend/services/$SERVICE_NAME start"]
