FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN CI=true pnpm install --frozen-lockfile --config.confirmModulesPurge=false
EXPOSE 3000
CMD ["pnpm", "-C", "backend/gateway", "start:dev"]
