FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN CI=true pnpm install --frozen-lockfile --config.confirmModulesPurge=false
EXPOSE 5173
CMD ["pnpm", "-C", "frontend/web", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
